const SHOP_DATA = {
  livingRoom: {
    id: 1,
    title: "office",
    routeName: "living-room",
    icon: "icon-living-room",
    items: [
      {
        id: 1,
        name: "blue living room",
        imageUrl: "https://i.ibb.co/vX1vBMR/living-room.png",
        price: 300,
        size: "large",
        type: "living room",
        recomended: "big couch",
      },
      {
        id: 2,
        name: "oily living room",
        imageUrl: "https://i.ibb.co/Qj69kW9/living-room-1.png",
        price: 250,
        size: "large",
        type: "living room",
        recomended: "big couch",
      },
      {
        id: 3,
        name: "brown living room",
        imageUrl: "https://i.ibb.co/Svz2bKb/living-room-2.png",
        price: 350,
        size: "large",
        type: "living room",
        recomended: "big couch",
      },
      {
        id: 4,
        name: "grey living room",
        imageUrl: "https://i.ibb.co/nCvbrd0/white-living-room.png",
        price: 150,
        size: "large",
        type: "living room",
        recomended: "big couch",
      },
      {
        id: 5,
        name: "yellow couch",
        imageUrl: "https://i.ibb.co/jRPNP9G/big-yellow-couch.png",
        price: 60,
        size: "medium",
        type: "living room",
        recomended: "medium couch",
      },
      {
        id: 6,
        name: "gray couche ",
        imageUrl: "https://i.ibb.co/TH2wjPR/pngwing-com-3.png",
        price: 80,
        size: "medium",
        type: "living room",
        recomended: "medium couch",
      },
      {
        id: 7,
        name: "white couch",
        imageUrl: "https://i.ibb.co/BPb1WtM/big-white-couch.png",
        price: 90,
        size: "medium",
        type: "living room",
        recomended: "medium couch",
      },
      {
        id: 8,
        name: "brown couch",
        imageUrl: "https://i.ibb.co/f2ckfqr/brown-couch.png",
        price: 50,
        size: "medium",
        type: "living room",
        recomended: "medium couch",
      },
      {
        id: 9,
        name: "yellow couch",
        imageUrl: "https://i.ibb.co/GWSLvY9/yellow-couch.png",
        price: 30,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
      {
        id: 10,
        name: "gray couch",
        imageUrl: "https://i.ibb.co/5Gz7LB7/gray-couch-2.png",
        price: 25,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
      {
        id: 11,
        name: "green couch",
        imageUrl: "https://i.ibb.co/dtgmMkB/green-couch.png",
        price: 40,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
      {
        id: 12,
        name: "blue couch",
        imageUrl: "https://i.ibb.co/stnCX6B/blue-couch.png",
        price: 60,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
      {
        id: 13,
        name: "white couch",
        imageUrl: "https://i.ibb.co/02HV3XF/white-couch.png",
        price: 30,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
      {
        id: 14,
        name: "double couch",
        imageUrl: "https://i.ibb.co/C2hZRKS/pngwing-com-9.png",
        price: 60,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
      {
        id: 15,
        name: "rose couch",
        imageUrl: "https://i.ibb.co/0KsvCSS/pngwing-com-3.png",
        price: 50,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
      {
        id: 16,
        name: "red couch",
        imageUrl: "https://i.ibb.co/64dzQBf/pngwing-com-5.png",
        price: 50,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
      {
        id: 17,
        name: "modern couch",
        imageUrl: "https://i.ibb.co/tZd1prs/pngwing-com-6.png",
        price: 30,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
      {
        id: 18,
        name: "dark gray couch",
        imageUrl: "https://i.ibb.co/RCktsW4/pngwing-com-2.png",
        price: 30,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
      {
        id: 19,
        name: "modern gray couch",
        imageUrl: "https://i.ibb.co/LCfMNdL/pngwing-com-14.png",
        price: 35,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
      {
        id: 20,
        name: "modern green couch",
        imageUrl: "https://i.ibb.co/tQD2dnC/pngwing-com-10.png",
        price: 37,
        size: "small",
        type: "living room",
        recomended: "small couch",
      },
    ],
  },
  office: {
    id: 2,
    title: "office",
    routeName: "office",
    icon: "icon-office",
    items: [
      {
        id: 21,
        name: "dark brown desk",
        imageUrl: "https://i.ibb.co/h2XvVNV/big-desk-2.png",
        price: 600,
        size: "large",
        type: "office",
        recomended: "desk",
      },
      {
        id: 22,
        name: "big wooden desk",
        imageUrl: "https://i.ibb.co/1mdwCcD/meeting-desk.png",
        price: 200,
        size: "large",
        type: "office",
        recomended: "desk",
      },
      {
        id: 23,
        name: "orange desk",
        imageUrl: "https://i.ibb.co/8dyCQCM/orange-desk.png",
        price: 700,
        size: "large",
        type: "office",
        recomended: "desk",
      },
      {
        id: 24,
        name: "big meeting table",
        imageUrl: "https://i.ibb.co/ypXNTrV/big-meeting-table.png",
        price: 950,
        size: "large",
        type: "office",
        recomended: "meeting table",
      },
      {
        id: 25,
        name: "meeting desk",
        imageUrl: "https://i.ibb.co/tYQZ4G1/m-meeting-table.png",
        price: 350,
        size: "medium",
        type: "office",
        recomended: "meeting table",
      },
      {
        id: 26,
        name: "dark desk ",
        imageUrl: "https://i.ibb.co/0Zpr84T/table.png",
        price: 150,
        size: "medium",
        type: "office",
        recomended: "desk",
      },
      {
        id: 27,
        name: "white desk",
        imageUrl: "https://i.ibb.co/0njqHDf/white-table.png",
        price: 550,
        size: "medium",
        type: "office",
        recomended: "desk",
      },
      {
        id: 28,
        name: "waiting seat",
        imageUrl: "https://i.ibb.co/sJfkLp6/wating-seat.png",
        price: 250,
        size: "medium",
        type: "office",
        recomended: "seat",
      },
      {
        id: 29,
        name: "Wheeled seat",
        imageUrl: "https://i.ibb.co/Kq6tkCJ/black-office-seat.png",
        price: 150,
        size: "small",
        type: "office",
        recomended: "seat",
      },
      {
        id: 30,
        name: "black seat",
        imageUrl: "https://i.ibb.co/DKCdhRD/black-seat.png",
        price: 120,
        size: "small",
        type: "office",
        recomended: "seat",
      },
      {
        id: 31,
        name: "brown wheeled seat",
        imageUrl: "https://i.ibb.co/V2Q09MQ/brown-office-seat.png",
        price: 170,
        size: "small",
        type: "office",
        recomended: "seat",
      },
      {
        id: 32,
        name: "brown seat",
        imageUrl: "https://i.ibb.co/gg1gPnq/brown-seat.png",
        price: 130,
        size: "small",
        type: "office",
        recomended: "seat",
      },
      {
        id: 33,
        name: "orange seat",
        imageUrl: "https://i.ibb.co/bzJmVzp/orange-seat.png",
        price: 28,
        size: "small",
        type: "office",
        recomended: "sea",
      },
      {
        id: 34,
        name: "wooden seat",
        imageUrl: "https://i.ibb.co/hHS6Bbk/wooden-seat.png",
        price: 15,
        size: "small",
        type: "office",
        recomended: "seat",
      },
      {
        id: 35,
        name: "simple seat",
        imageUrl: "https://i.ibb.co/1KjJ8mm/desk-seat.png",
        price: 25,
        size: "small",
        type: "office",
        recomended: "seat",
      },
      {
        id: 36,
        name: "sky seat",
        imageUrl: "https://i.ibb.co/zQHrtJh/sky-seat.png",
        price: 10,
        size: "small",
        type: "office",
        recomended: "seat",
      },
      {
        id: 37,
        name: "modern seat",
        imageUrl: "https://i.ibb.co/pjJ41BD/pngwing-com-3.png",
        price: 30,
        size: "small",
        type: "office",
        recomended: "seat",
      },
      {
        id: 38,
        name: "gray seat",
        imageUrl: "https://i.ibb.co/qdcwMBV/pngwing-com-2.png",
        price: 13,
        size: "small",
        type: "office",
        recomended: "seat",
      },
      {
        id: 39,
        name: "beige seat",
        imageUrl: "https://i.ibb.co/SQKTgdD/light-brown-seat.png",
        price: 170,
        size: "small",
        type: "office",
        recomended: "seat",
      },
      {
        id: 40,
        name: "modern dark seat",
        imageUrl: "https://i.ibb.co/ByHcKbd/pngwing-com-1.png",
        price: 90,
        size: "small",
        type: "office",
        recomended: "seat",
      },
    ],
  },
  bedRoom: {
    id: 3,
    title: "bed room",
    routeName: "bed-room",
    icon: "bed-room",
    items: [
      {
        id: 41,
        name: "brown bed",
        imageUrl: "https://i.ibb.co/60bVKjS/pngwing-com-20.png",
        price: 800,
        size: "large",
        type: "bed room",
        recomended: "bed",
      },
      {
        id: 42,
        name: "b modern cupbord",
        imageUrl: "https://i.ibb.co/xj7kgdf/pngwing-com-15.png",
        price: 1500,
        size: "large",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 43,
        name: "modern bed",
        imageUrl: "https://i.ibb.co/QCX4nrg/pngwing-com-21.png",
        price: 1999,
        size: "large",
        type: "bed room",
        recomended: "bed",
      },
      {
        id: 44,
        name: "green bed",
        imageUrl: "https://i.ibb.co/dgrHydT/pngwing-com-23.png",
        price: 360,
        size: "large",
        type: "bed room",
        recomended: "bed",
      },
      {
        id: 45,
        name: "blue bed",
        imageUrl: "https://i.ibb.co/9TJhtfg/pngwing-com-22.png",
        price: 250,
        size: "medium",
        type: "bed room",
        recomended: "bed",
      },
      {
        id: 46,
        name: "gray bed",
        imageUrl: "https://i.ibb.co/d65wp6m/pngwing-com-14.png",
        price: 250,
        size: "medium",
        type: "bed room",
        recomended: "bed",
      },
      {
        id: 47,
        name: "white bed",
        imageUrl: "https://i.ibb.co/BVxdVTx/pngwing-com-16.png",
        price: 200,
        size: "medium",
        type: "bed room",
        recomended: "bed",
      },
      {
        id: 48,
        name: "white cupbord",
        imageUrl: "https://i.ibb.co/Pg2HvxJ/pngwing-com-6.png",
        price: 600,
        size: "medium",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 49,
        name: "wooden cupbord",
        imageUrl: "https://i.ibb.co/m687MHY/pngwing-com-1.png",
        price: 150,
        size: "small",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 50,
        name: "white cupbord",
        imageUrl: "https://i.ibb.co/64DNMdN/pngwing-com-3.png",
        price: 180,
        size: "small",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 51,
        name: "brown cupbord",
        imageUrl: "https://i.ibb.co/mJ78PSW/pngwing-com-2.png",
        price: 170,
        size: "small",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 52,
        name: "simple cupbord",
        imageUrl: "https://i.ibb.co/V2hswQf/pngwing-com-7.png",
        price: 130,
        size: "small",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 53,
        name: "modern cupbord",
        imageUrl: "https://i.ibb.co/7xcjrW9/pngwing-com-5.png",
        price: 200,
        size: "small",
        type: "bed room",
        recomended: "sea",
      },
      {
        id: 54,
        name: "wooden cupbord",
        imageUrl: "https://i.ibb.co/hHS6Bbk/wooden-cupbord.png",
        price: 15,
        size: "small",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 55,
        name: "simple cupbord",
        imageUrl: "https://i.ibb.co/1KjJ8mm/desk-cupbord.png",
        price: 25,
        size: "small",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 56,
        name: "small cupbord",
        imageUrl: "https://i.ibb.co/z7gxRFr/pngwing-com-9.png",
        price: 50,
        size: "small",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 57,
        name: "white cupbord",
        imageUrl: "https://i.ibb.co/s6CS46N/pngwing-com-10.png",
        price: 180,
        size: "small",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 58,
        name: "red cupbord",
        imageUrl: "https://i.ibb.co/xSgDDmf/pngwing-com-11.png",
        price: 120,
        size: "small",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 59,
        name: "dark cupbord",
        imageUrl: "https://i.ibb.co/nrYY5V4/pngwing-com-13.png",
        price: 170,
        size: "small",
        type: "bed room",
        recomended: "cupbord",
      },
      {
        id: 60,
        name: "modern dark cupbord",
        imageUrl: "https://i.ibb.co/k43WkhC/pngwing-com-12.png",
        price: 220,
        size: "small",
        type: "bed room",
        recomended: "cupbord",
      },
    ],
  },
  forKids: {
    id: 4,
    title: "for kids",
    routeName: "for-kids",
    icon: "icon-kids-room",
    items: [
      {
        id: 71,
        name: "wooden bed",
        imageUrl: "https://i.ibb.co/ncNnZkp/pngwing-com-8.png",
        price: 900,
        size: "large",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 72,
        name: "ship bed",
        imageUrl: "https://i.ibb.co/3hTz7jr/ship-bed.png",
        price: 1150,
        size: "large",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 73,
        name: "dark bed",
        imageUrl: "https://i.ibb.co/zQbWy3J/pngwing-com-10.png",
        price: 1000,
        size: "large",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 74,
        name: "girls bed",
        imageUrl: "https://i.ibb.co/qxxbfW1/stairs-bed.png",
        price: 1150,
        size: "large",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 75,
        name: "bink bed",
        imageUrl: "https://i.ibb.co/LpZyWBB/pngwing-com-1.png",
        price: 500,
        size: "medium",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 76,
        name: "wooden bed",
        imageUrl: "https://i.ibb.co/Js2Wpk3/pngwing-com-9.png",
        price: 250,
        size: "medium",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 77,
        name: "boys bed",
        imageUrl: "https://i.ibb.co/VqF78yj/pngwing-com-7.png",
        price: 600,
        size: "medium",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 78,
        name: "white bed",
        imageUrl: "https://i.ibb.co/nDY4cMc/pngwing-com-4.png",
        price: 650,
        size: "medium",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 79,
        name: "horse",
        imageUrl: "https://i.ibb.co/C9rQnJx/horse.jpg",
        price: 150,
        size: "small",
        type: "for kids",
        recomended: "kids toy",
      },
      {
        id: 80,
        name: "kids table",
        imageUrl: "https://i.ibb.co/zQrnxh7/kids-table.png",
        price: 180,
        size: "small",
        type: "for kids",
        recomended: "kids table",
      },
      {
        id: 81,
        name: "s kids table",
        imageUrl: "https://i.ibb.co/d6HgW04/pngwing-com-12.png",
        price: 170,
        size: "small",
        type: "for kids",
        recomended: "kids table",
      },
      {
        id: 82,
        name: "kids table",
        imageUrl: "https://i.ibb.co/sbB2r2t/play-table.png",
        price: 130,
        size: "small",
        type: "for kids",
        recomended: "kids table",
      },
      {
        id: 83,
        name: "toy",
        imageUrl: "https://i.ibb.co/BLhpnsG/kids-toy.png",
        price: 200,
        size: "small",
        type: "for kids",
        recomended: "kids toy",
      },
      {
        id: 84,
        name: "kids car",
        imageUrl: "https://i.ibb.co/pKwZ9yX/babe-car.png",
        price: 150,
        size: "small",
        type: "for kids",
        recomended: "kids toy",
      },
      {
        id: 85,
        name: "pyano",
        imageUrl: "https://i.ibb.co/SR2JKSP/pyano.png",
        price: 25,
        size: "small",
        type: "for kids",
        recomended: "kids toy",
      },
      {
        id: 86,
        name: "kids bed",
        imageUrl: "https://i.ibb.co/Qb7gnwM/pngwing-com-6.png",
        price: 50,
        size: "small",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 87,
        name: "white bed",
        imageUrl: "https://i.ibb.co/W0spkKb/pngwing-com-3.png",
        price: 180,
        size: "small",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 88,
        name: "girls bed",
        imageUrl: "https://i.ibb.co/kGM2YKx/two-bed.png",
        price: 120,
        size: "small",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 89,
        name: "kids bed",
        imageUrl: "https://i.ibb.co/c2DrLC6/kindpng-4001956.png",
        price: 170,
        size: "small",
        type: "for kids",
        recomended: "kids bed",
      },
      {
        id: 90,
        name: "wooden bed",
        imageUrl: "https://i.ibb.co/Js2Wpk3/pngwing-com-9.png",
        price: 220,
        size: "small",
        type: "for kids",
        recomended: "kids bed",
      },
    ],
  },
  kitchen: {
    id: 5,
    title: "kitchen",
    routeName: "kitchen",
    icon: "icon-kitchen",
    items: [
      {
        id: 91,
        name: "big cupbord",
        imageUrl: "https://i.ibb.co/wppgksY/big-cabinet.png",
        price: 1500,
        size: "large",
        type: "kitchen",
        recomended: "kitchen cupbord",
      },
      {
        id: 92,
        name: "wooden cabinet",
        imageUrl: "https://i.ibb.co/YjXygRw/wooden-cabinet.png",
        price: 1100,
        size: "large",
        type: "kitchen",
        recomended: "kitchen cupbord",
      },
      {
        id: 93,
        name: "green cabinet",
        imageUrl: "https://i.ibb.co/QCX4nrg/pngwing-com-21.png",
        price: 1999,
        size: "large",
        type: "kitchen",
        recomended: "kitchen cupbord",
      },
      {
        id: 94,
        name: "dish cupboard",
        imageUrl: "https://i.ibb.co/s32wMJG/high-cabinet.png",
        price: 750,
        size: "large",
        type: "kitchen",
        recomended: "kitchen cupbord",
      },
      {
        id: 95,
        name: "wall cabinet",
        imageUrl: "https://i.ibb.co/0YVdNdD/wall-cabinet-2.pngg",
        price: 250,
        size: "medium",
        type: "kitchen",
        recomended: "kitchen cupbord",
      },
      {
        id: 96,
        name: "eating table",
        imageUrl: "https://i.ibb.co/4PfMB37/table.png",
        price: 200,
        size: "medium",
        type: "kitchen",
        recomended: "kitchen table",
      },
      {
        id: 97,
        name: "Towel closet",
        imageUrl: "https://i.ibb.co/mRD6qzq/towel-cabinet.png",
        price: 300,
        size: "medium",
        type: "kitchen",
        recomended: "kitchen cupbord",
      },
      {
        id: 98,
        name: "high cabinet",
        imageUrl: "https://i.ibb.co/s32wMJG/high-cabinet.png",
        price: 600,
        size: "medium",
        type: "kitchen",
        recomended: "kitchen cupbord",
      },
      {
        id: 99,
        name: "Wood spoon",
        imageUrl: "https://i.ibb.co/jvQw1jw/spoon.png",
        price: 25,
        size: "small",
        type: "kitchen",
        recomended: "kitchen tools",
      },
      {
        id: 100,
        name: "Wooden dishes",
        imageUrl: "https://i.ibb.co/PtRjWpD/Soup-dish.png",
        price: 20,
        size: "small",
        type: "kitchen",
        recomended: "kitchen tools",
      },
      {
        id: 101,
        name: "Knife holder",
        imageUrl: "https://i.ibb.co/b7C0ktz/brown-wooden-stand.png",
        price: 35,
        size: "small",
        type: "kitchen",
        recomended: "kitchen tools",
      },
      {
        id: 102,
        name: "spoons",
        imageUrl: "https://i.ibb.co/sm6DHzn/hiclipart-com-2.png",
        price: 30,
        size: "small",
        type: "kitchen",
        recomended: "kitchen tools",
      },
      {
        id: 103,
        name: "Knife holder",
        imageUrl: "https://i.ibb.co/gR5wsjr/wodden-stand.png",
        price: 40,
        size: "small",
        type: "kitchen",
        recomended: "kitchen tools",
      },
      {
        id: 104,
        name: "wooden spoons",
        imageUrl: "https://i.ibb.co/7R9zm70/wood-spoon.png",
        price: 15,
        size: "small",
        type: "kitchen",
        recomended: "kitchen tools",
      },
      {
        id: 105,
        name: "table",
        imageUrl: "https://i.ibb.co/fN8bDgt/date-table.png",
        price: 100,
        size: "small",
        type: "kitchen",
        recomended: "kitchen table",
      },
      {
        id: 106,
        name: "Knife holder",
        imageUrl: "https://i.ibb.co/b7C0ktz/brown-wooden-stand.png",
        price: 30,
        size: "small",
        type: "kitchen",
        recomended: "kitchen tools",
      },
      {
        id: 107,
        name: "spoons",
        imageUrl: "https://i.ibb.co/sm6DHzn/hiclipart-com-2.png",
        price: 30,
        size: "small",
        type: "kitchen",
        recomended: "kitchen tools",
      },
      {
        id: 108,
        name: "Knife holder",
        imageUrl: "https://i.ibb.co/gR5wsjr/wodden-stand.png",
        price: 50,
        size: "small",
        type: "kitchen",
        recomended: "kitchen tools",
      },
      {
        id: 109,
        name: "wooden spoons",
        imageUrl: "https://i.ibb.co/7R9zm70/wood-spoon.png",
        price: 15,
        size: "small",
        type: "kitchen",
        recomended: "kitchen tools",
      },
      {
        id: 110,
        name: "spoons",
        imageUrl: "https://i.ibb.co/sm6DHzn/hiclipart-com-2.png",
        price: 30,
        size: "small",
        type: "kitchen",
        recomended: "kitchen tools",
      },
    ],
  },
  accessories: {
    id: 6,
    title: "accessories",
    routeName: "accessories",
    icon: "icon-accessories",
    items: [
      {
        id: 111,
        name: "glass lamp",
        imageUrl: "https://i.ibb.co/546hLCH/pngwing-com-3.png",
        price: 200,
        size: "large",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 112,
        name: "lamp",
        imageUrl:
          "https://i.ibb.co/2SFMhH2/kisspng-table-electric-light-crystal-lamp-3d-model-crystal-table-lamps-5aaef162741149-4661504015214144984754.png",
        price: 150,
        size: "large",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 113,
        name: "Chandeliers",
        imageUrl: "https://i.ibb.co/wgW3J3x/pngflow-com.png",
        price: 350,
        size: "large",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 114,
        name: "white lamp",
        imageUrl: "https://i.ibb.co/FbfPpy7/pngwing-com-4.png",
        price: 360,
        size: "large",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 115,
        name: "glass lamp",
        imageUrl: "https://i.ibb.co/P6ngMCJ/pngwing-com-2.png",
        price: 150,
        size: "medium",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 116,
        name: "Chandeliers",
        imageUrl: "https://i.ibb.co/HYsBvLC/pngwing-com-5.png",
        price: 250,
        size: "medium",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 117,
        name: "lamp",
        imageUrl: "https://i.ibb.co/kctWjgG/pngwing-com-9.png",
        price: 200,
        size: "medium",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 118,
        name: "wall lamp",
        imageUrl: "https://i.ibb.co/m9tf1sL/pngwing-com-10.png",
        price: 600,
        size: "medium",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 119,
        name: "blask lamp",
        imageUrl: "https://i.ibb.co/TLC0tQq/pngwing-com-7.png",
        price: 150,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 120,
        name: "desk lamp",
        imageUrl: "https://i.ibb.co/MZwPCHC/pngwing-com-6.png",
        price: 180,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 121,
        name: "stand lamp",
        imageUrl: "https://i.ibb.co/kctWjgG/pngwing-com-9.png",
        price: 170,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 122,
        name: "blue lamp",
        imageUrl: "https://i.ibb.co/3BF7DYf/pngwing-com-1.png",
        price: 130,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 123,
        name: "wall watch",
        imageUrl: "https://i.ibb.co/JCVZXDz/pngflow-com-1.png",
        price: 200,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 124,
        name: "golden lamb",
        imageUrl: "https://i.ibb.co/C9rPrxj/pngwing-com-11.png",
        price: 350,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 125,
        name: "blask lamp",
        imageUrl: "https://i.ibb.co/TLC0tQq/pngwing-com-7.png",
        price: 150,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 126,
        name: "desk lamp",
        imageUrl: "https://i.ibb.co/MZwPCHC/pngwing-com-6.png",
        price: 180,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 127,
        name: "stand lamp",
        imageUrl: "https://i.ibb.co/kctWjgG/pngwing-com-9.png",
        price: 170,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 128,
        name: "blue lamp",
        imageUrl: "https://i.ibb.co/3BF7DYf/pngwing-com-1.png",
        price: 130,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 129,
        name: "wall watch",
        imageUrl: "https://i.ibb.co/JCVZXDz/pngflow-com-1.png",
        price: 200,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
      {
        id: 130,
        name: "golden lamb",
        imageUrl: "https://i.ibb.co/C9rPrxj/pngwing-com-11.png",
        price: 350,
        size: "small",
        type: "accessories",
        recomended: "lamb",
      },
    ],
  },
};

export default SHOP_DATA;
