const SHOP_DATA = {
  data: {
    items: [
      {
        id: 1,
        name: "blue living room",
        imageUrl: "https://i.ibb.co/HHxpM81/blue-living-room.png",
        price: 300,
        size: "large",
        type: "living room",
        url: "living-room",
        recomended: "big couch",
        link: "blue-living-room",
        like: 250,
        discount: 50,
        Piece: 2,
      },
      {
        id: 2,
        name: "dark brown desk",
        imageUrl: "https://i.ibb.co/pzQVywr/big-desk-2.png",
        price: 600,
        size: "large",
        type: "office",
        url: "office",
        recomended: "desk",
        link: "dark-brown-desk",
        like: 220,
        discount: 10,
        Piece: 6,
      },
      {
        id: 3,
        name: "brown wheeled seat",
        imageUrl: "https://i.ibb.co/8m1GyGy/brown-office-seat.png",
        price: 170,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "brown-wheeled-seat",
        like: 150,
        discount: 10,
        Piece: 2,
      },
      {
        id: 4,
        name: "black lamp",
        imageUrl: "https://i.ibb.co/CQy0HZM/pngwing-com-7.png",
        price: 150,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "black-lamp",
        like: 210,
        discount: 10,
        Piece: 4,
      },

      {
        id: 5,
        name: "oily living room",
        imageUrl: "https://i.ibb.co/G0jvgnk/oliy-living-room.png",
        price: 250,
        size: "large",
        type: "living room",
        url: "living-room",
        recomended: "big couch",
        link: "oily-living-room",
        like: 110,
        discount: 10,
        Piece: 4,
      },
      {
        id: 6,
        name: "green bed",
        imageUrl: "https://i.ibb.co/F3FycWk/pngwing-com-23.png",
        price: 360,
        size: "large",
        type: "bed room",
        url: "bed-room",
        recomended: "bed",
        link: "green-bed",
        like: 50,
        discount: 10,
        Piece: 7,
      },
      {
        id: 7,
        name: "wooden cabinet",
        imageUrl: "https://i.ibb.co/RC0JF57/wooden-cabinet.png",
        price: 1100,
        size: "large",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen cupbord",
        link: "wooden-cabinet",
        like: 30,
        discount: 10,
        Piece: 5,
      },
      {
        id: 8,
        name: "Chandeliers 1",
        imageUrl: "https://i.ibb.co/QnfFrpR/pngflow.png",
        price: 350,
        size: "large",
        type: "accessories",
        url: "accessories",
        recomended: "Chandeliers",
        link: "Chandeliers-1",
        like: 70,
        discount: 10,
        Piece: 4,
      },
      {
        id: 9,
        name: "dish cupboard",
        imageUrl: "https://i.ibb.co/9g33MCc/high-cabinet.png",
        price: 750,
        size: "large",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen cupbord",
        link: "dish-cupboard",
        like: 450,
        discount: 10,
        Piece: 10,
      },
      {
        id: 10,
        name: "wooden seat",
        imageUrl: "https://i.ibb.co/FKdVTzj/pngwing-com-3.png",
        price: 15,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "wooden-seat",
        like: 10,
        discount: 10,
        Piece: 6,
      },
      {
        id: 11,
        name: "kids bed",
        imageUrl: "https://i.ibb.co/s5gKc6D/kindpng-4001956.png",
        price: 170,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "kids-bed",
        like: 2,
        discount: 10,
        Piece: 10,
      },
      {
        id: 12,
        name: "brown living room",
        imageUrl: "https://i.ibb.co/6Pms70D/brown-living-room.png",
        price: 350,
        size: "large",
        type: "living room",
        url: "living-room",
        recomended: "big couch",
        link: "brown-living-room",
        like: 5,
        discount: 10,
        Piece: 3,
      },
      {
        id: 13,
        name: "modern bed",
        imageUrl: "https://i.ibb.co/ssWFqbk/pngwing-com-26.png",
        price: 1999,
        size: "large",
        type: "bed room",
        url: "bed-room",
        recomended: "bed",
        link: "modern bed",
        like: 29,
        discount: 10,
        Piece: 7,
      },
      {
        id: 14,
        name: "boys bed",
        imageUrl: "https://i.ibb.co/9pkjgdw/stairs-bed.png",
        price: 600,
        size: "medium",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "boys-bed",
        like: 25,
        discount: 10,
        Piece: 6,
      },
      {
        id: 15,
        name: "green cabinet",
        imageUrl: "https://i.ibb.co/XSTWZ94/green-cabinet.png",
        price: 1999,
        size: "large",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen cupbord",
        link: "green-cabinet",
        like: 65,
        discount: 10,
        Piece: 1,
      },
      {
        id: 16,
        name: "kids table",
        imageUrl: "https://i.ibb.co/MPJxckd/kids-table.png",
        price: 180,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids table",
        link: "kids-table",
        like: 40,
        discount: 10,
        Piece: 4,
      },
      {
        id: 17,
        name: "dark gray couch",
        imageUrl: "https://i.ibb.co/WcCX2px/dark-gray-couch.png",
        price: 150,
        size: "large",
        type: "living room",
        url: "living-room",
        recomended: "big couch",
        link: "dark-gray-couch",
        like: 60,
        discount: 10,
        Piece: 7,
      },
      {
        id: 18,
        name: "white bed",
        imageUrl: "https://i.ibb.co/pyr5WYb/pngwing-com-4.png",
        price: 650,
        size: "medium",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "white-bed",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 19,
        name: "Wooden dishes",
        imageUrl: "https://i.ibb.co/1TJWr0K/Soup-dish.png",
        price: 20,
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen tools",
        link: "Wooden-dishes",
        like: 60,
        discount: 10,
        Piece: 7,
      },
      {
        id: 20,
        name: "Knife holder",
        imageUrl: "https://i.ibb.co/CW1MS1g/brown-wooden-stand.png",
        price: 35,
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen tools",
        link: "Knife-holder",
        like: 60,
        discount: 10,
        Piece: 2,
      },
      {
        id: 21,
        name: "roof lamp 2",
        imageUrl: "https://i.ibb.co/6FNnjkc/pngwing-com-14.png",
        price: 150,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "roof-lamp-2",
        like: 60,
        discount: 10,
        Piece: 7,
      },
      {
        id: 22,
        name: "roof lamp 3",
        imageUrl: "https://i.ibb.co/z2sTDhQ/pngwing-com-16.png",
        price: 180,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "roof-lamp-3",
        like: 18,
        discount: 10,
        Piece: 46,
      },
      {
        id: 23,
        name: "big yellow couch",
        imageUrl: "https://i.ibb.co/f1YS7K3/big-yellow-couch.png",
        price: 60,
        size: "medium",
        type: "living room",
        url: "living-room",
        recomended: "medium couch",
        link: "yellow-couch",
        like: 18,
        discount: 10,
        Piece: 8,
      },
      {
        id: 24,
        name: "big wooden desk",
        imageUrl: "https://i.ibb.co/v1QVRh8/big-desk.png",
        price: 200,
        size: "large",
        type: "office",
        url: "office",
        recomended: "desk",
        link: "big-wooden-desk",
        like: 18,
        discount: 10,
        Piece: 10,
      },
      {
        id: 25,
        name: "big gray couche",
        imageUrl: "https://i.ibb.co/TbQLwzD/gray-couch.png",
        price: 80,
        size: "medium",
        type: "living room",
        url: "living-room",
        recomended: "medium couch",
        link: "big-gray-couche",
        like: 18,
        discount: 10,
        Piece: 10,
      },
      {
        id: 26,
        name: "orange desk",
        imageUrl: "https://i.ibb.co/WcmLCBS/orange-desk.png",
        price: 700,
        size: "large",
        type: "office",
        url: "office",
        recomended: "desk",
        link: "orange-desk",
        like: 18,
        discount: 10,
        Piece: 10,
      },
      {
        id: 27,
        name: "simple cupbord",
        imageUrl: "https://i.ibb.co/T2f1BY0/pngwing-com-7.png",
        price: 130,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "simple-cupbord",
        like: 18,
        discount: 10,
        Piece: 10,
      },
      {
        id: 28,
        name: "modern cupbord",
        imageUrl: "https://i.ibb.co/3MK7mgL/pngwing-com-5.png",
        price: 200,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "modern-cupbord",
        like: 18,
        discount: 10,
        Piece: 10,
      },
      {
        id: 29,
        name: "white bed",
        imageUrl: "https://i.ibb.co/f0XKKFc/pngwing-com-16.png",
        price: 200,
        size: "medium",
        type: "bed room",
        url: "bed-room",
        recomended: "bed",
        link: "white-bed",
        like: 18,
        discount: 10,
        Piece: 10,
      },
      {
        id: 30,
        name: "white cupbord",
        imageUrl: "https://i.ibb.co/89TKRK7/pngwing-com-6.png",
        price: 600,
        size: "medium",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "white-cupbord",
        like: 18,
        discount: 10,
        Piece: 10,
      },
      {
        id: 31,
        name: "white couch",
        imageUrl: "https://i.ibb.co/wsJ7W0R/white-couch.png",
        price: 90,
        size: "medium",
        type: "living room",
        url: "living-room",
        recomended: "medium couch",
        link: "white-couch",
        like: 18,
        discount: 10,
        Piece: 10,
      },
      {
        id: 32,
        name: "dark bed",
        imageUrl: "https://i.ibb.co/dJBPxd1/pngwing-com-10.png",
        price: 1000,
        size: "large",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "dark-bed",
        like: 18,
        discount: 10,
        Piece: 10,
      },
      {
        id: 33,
        name: "girls bed",
        imageUrl: "https://i.ibb.co/F39Jh3S/pngwing-com-5.png",
        price: 1150,
        size: "large",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "girls-bed",
        like: 18,
        discount: 10,
        Piece: 10,
      },
      {
        id: 34,
        name: "gray seat",
        imageUrl: "https://i.ibb.co/vHK9HfD/pngwing-com-2.png",
        price: 13,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "gray-seat",
        like: 15,
        discount: 10,
        Piece: 10,
      },
      {
        id: 35,
        name: "beige seat",
        imageUrl: "https://i.ibb.co/g4PdnVm/light-brown-seat.png",
        price: 170,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "beige-seat",
        like: 15,
        discount: 10,
        Piece: 10,
      },
      {
        id: 36,
        name: "modern dark seat",
        imageUrl: "https://i.ibb.co/xGY4M7B/black-seat.png",
        price: 90,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "modern-dark-seat",
        like: 15,
        discount: 10,
        Piece: 10,
      },
      {
        id: 37,
        name: "white lamp",
        imageUrl: "https://i.ibb.co/k31TzRh/pngwing-com-4.png",
        price: 360,
        size: "large",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "white-lamp",
        like: 125,
        discount: 10,
        Piece: 10,
      },
      {
        id: 38,
        name: "glass lamp 2",
        imageUrl: "https://i.ibb.co/cx642vQ/pngwing-com-2.png",
        price: 150,
        size: "medium",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "glass-lamp-2",
        like: 15,
        discount: 10,
        Piece: 10,
      },
      {
        id: 39,
        name: "Chandeliers 2",
        imageUrl: "https://i.ibb.co/s27FzQq/pngwing-com-5.png",
        price: 250,
        size: "medium",
        type: "accessories",
        url: "accessories",
        recomended: "Chandeliers",
        link: "Chandeliers-2",
        like: 60,
        discount: 10,
        Piece: 5,
      },
      {
        id: 40,
        name: "brown couch",
        imageUrl: "https://i.ibb.co/X3bH1fT/pngwing-com-13.png",
        price: 50,
        size: "medium",
        type: "living room",
        url: "living-room",
        recomended: "medium couch",
        link: "brown-couch",
        like: 60,
        discount: 10,
        Piece: 5,
      },
      {
        id: 41,
        name: "small yellow couch",
        imageUrl: "https://i.ibb.co/m4DpxhS/yellow-couch.png",
        price: 300,
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "small-yellow-couch",
        like: 60,
        discount: 50,
        Piece: 5,
      },
      {
        id: 42,
        name: "blue bed",
        imageUrl: "https://i.ibb.co/ypY7HWh/pngwing-com-22.png",
        price: 250,
        size: "medium",
        type: "bed room",
        url: "bed-room",
        recomended: "bed",
        link: "blue-bed",
        like: 10,
        discount: 10,
        Piece: 5,
      },
      {
        id: 43,
        name: "brown seat",
        imageUrl: "https://i.ibb.co/HGC5tnG/brown-seat.png",
        price: 130,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "brown-seat",
        like: 10,
        discount: 10,
        Piece: 5,
      },
      {
        id: 44,
        name: "gray bed",
        imageUrl: "https://i.ibb.co/vZV3CT7/pngwing-com-14.png",
        price: 250,
        size: "medium",
        type: "bed room",
        url: "bed-room",
        recomended: "bed",
        link: "gray-bed",
        like: 10,
        discount: 10,
        Piece: 5,
      },
      {
        id: 45,
        name: "orange seat",
        imageUrl: "https://i.ibb.co/gwv9kCw/orange-seat.png",
        price: 28,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "orange-seat",
        like: 10,
        discount: 10,
        Piece: 5,
      },
      {
        id: 46,
        name: "wooden cupbord",
        imageUrl: "https://i.ibb.co/NnwMxvH/pngwing-com-15.png",
        price: 150,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "wooden-cupbord",
        like: 10,
        discount: 10,
        Piece: 5,
      },
      {
        id: 47,
        name: "simple gray couch",
        imageUrl: "https://i.ibb.co/RpFkcKx/simple-gray-couch.png",
        price: 25,
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "simple-gray-couch",
        like: 10,
        discount: 10,
        Piece: 5,
      },
      {
        id: 48,
        name: "black seat",
        imageUrl: "https://i.ibb.co/6tRVXgT/pngwing-com-1.png",
        price: 120,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "black-seat",
        like: 10,
        discount: 10,
        Piece: 41,
      },
      {
        id: 49,
        name: "simple seat",
        imageUrl: "https://i.ibb.co/vHK9HfD/pngwing-com-2.png",
        price: 25,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "simple-seat",
        like: 10,
        discount: 10,
        Piece: 41,
      },
      {
        id: 50,
        name: "s kids table",
        imageUrl: "https://i.ibb.co/rpgsFYD/pngwing-com-12.png",
        price: 170,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids table",
        link: "s-kids-table",
        like: 10,
        discount: 10,
        Piece: 41,
      },
      {
        id: 51,
        name: "red cupbord",
        imageUrl: "https://i.ibb.co/cCxg4F8/pngwing-com-11.png",
        price: 120,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "red-cupbord",
        like: 10,
        discount: 10,
        Piece: 41,
      },
      {
        id: 52,
        name: "play table",
        imageUrl: "https://i.ibb.co/WKSxj68/play-table.png",
        price: 130,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids table",
        link: "play-table",
        like: 10,
        discount: 10,
        Piece: 41,
      },
      {
        id: 53,
        name: "dark cupbord",
        imageUrl: "https://i.ibb.co/WWkG46f/pngwing-com-13.png",
        price: 170,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "dark-cupbord",
        like: 10,
        discount: 10,
        Piece: 41,
      },
      {
        id: 54,
        name: "Chandeliers 4",
        imageUrl: "https://i.ibb.co/X3bH1fT/pngwing-com-13.png",
        price: 200,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "Chandeliers",
        link: "Chandeliers-4",
        like: 10,
        discount: 10,
        Piece: 41,
      },
      {
        id: 55,
        name: "wall dark cabinet",
        imageUrl: "https://i.ibb.co/Vx2gfTh/big-high-cabinet.png",
        price: 30,
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen tools",
        link: "wall-dark-cabinet",
        like: 10,
        discount: 10,
        Piece: 41,
      },
      {
        id: 56,
        name: "small cabinet",
        imageUrl: "https://i.ibb.co/f9g41L9/base-cabinet.png",
        price: 30,
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen tools",
        link: "small-cabinet",
        like: 10,
        discount: 10,
        Piece: 15,
      },
      {
        id: 57,
        name: "Chandeliers 5",
        imageUrl: "https://i.ibb.co/0FmhW8n/pngwing-com-15.png",
        price: 350,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "Chandeliers",
        link: "Chandeliers-5",
        like: 50,
        discount: 10,
        Piece: 15,
      },
      {
        id: 58,
        name: "toy",
        imageUrl: "https://i.ibb.co/H2zc03H/kids-toy.png",
        price: 200,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids toy",
        link: "toy",
        like: 50,
        discount: 10,
        Piece: 15,
      },
      {
        id: 59,
        name: "desk lamp",
        imageUrl: "https://i.ibb.co/K9n9tnS/pngwing-com-6.png",
        price: 180,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "desk-lamp",
        like: 50,
        discount: 10,
        Piece: 15,
      },
      {
        id: 60,
        name: "green couch",
        imageUrl: "https://i.ibb.co/wsvTmhH/green-couch.png",
        price: 40,
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "green-couch",
        like: 50,
        discount: 10,
        Piece: 15,
      },
      {
        id: 61,
        name: "stand lamp",
        imageUrl: "https://i.ibb.co/YB1Fprd/pngwing-com-8.png",
        price: 170,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "stand-lamp",
        like: 50,
        discount: 10,
        Piece: 15,
      },
      {
        id: 62,
        name: "blue lamp",
        imageUrl: "https://i.ibb.co/xG47sWc/pngwing-com-1.png",
        price: 130,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "blue-lamp",
        like: 50,
        discount: 10,
        Piece: 15,
      },
      {
        id: 63,
        name: "big cabinet",
        imageUrl: "https://i.ibb.co/Xx1xpRx/big-cabinet.png",
        price: 1500,
        size: "large",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen cupbord",
        link: "big-cabinet",
        like: 50,
        discount: 10,
        Piece: 15,
      },
      {
        id: 64,
        name: "blue couch",
        imageUrl: "https://i.ibb.co/rkMyZHP/blue-couch.png",
        price: 60,
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "blue-couch",
        like: 50,
        discount: 10,
        Piece: 15,
      },
      {
        id: 65,
        name: "wall cabinet",
        imageUrl: "https://i.ibb.co/gy40X19/brown-cabinet.png",
        price: 250,
        size: "medium",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen cupbord",
        link: "wall-cabinet",
        like: 50,
        discount: 10,
        Piece: 3,
      },
      {
        id: 66,
        name: "eating table",
        imageUrl: "https://i.ibb.co/jrh3GX9/dinner-table.png",
        price: 200,
        size: "medium",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen table",
        link: "eating-table",
        like: 50,
        discount: 10,
        Piece: 3,
      },
      {
        id: 67,
        name: "sky blue seat",
        imageUrl: "https://i.ibb.co/RPNXn1L/sky-seat.png",
        price: 10,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "sky-blue-seat",
        like: 50,
        discount: 10,
        Piece: 3,
      },
      {
        id: 68,
        name: "modern seat",
        imageUrl: "https://i.ibb.co/xGY4M7B/black-seat.png",
        price: 30,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "modern-seat",
        like: 50,
        discount: 10,
        Piece: 3,
      },
      {
        id: 69,
        name: "bink bed",
        imageUrl: "https://i.ibb.co/wgMFv80/pngwing-com-1.png",
        price: 500,
        size: "medium",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "bink-bed",
        like: 50,
        discount: 10,
        Piece: 3,
      },
      {
        id: 70,
        name: "wooden bed",
        imageUrl: "https://i.ibb.co/FzyXt73/pngwing-com-9.png",
        price: 250,
        size: "medium",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "wooden-bed",
        like: 50,
        discount: 10,
        Piece: 3,
      },
      {
        id: 71,
        name: "waiting seat",
        imageUrl: "https://i.ibb.co/vZZB8rB/wating-seat.png",
        price: 250,
        size: "medium",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "waiting-seat",
        like: 50,
        discount: 10,
        Piece: 3,
      },
      {
        id: 72,
        name: "Wheeled seat",
        imageUrl: "https://i.ibb.co/vZZB8rB/wating-seat.png",
        price: 150,
        size: "small",
        type: "office",
        url: "office",
        recomended: "seat",
        link: "Wheeled-seat",
        like: 50,
        discount: 10,
        Piece: 3,
      },
      {
        id: 73,
        name: "simple couch",
        imageUrl: "https://i.ibb.co/nn5d4Hv/simple-couch.png",
        price: 30,
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "simple-couch",
        like: 50,
        discount: 10,
        Piece: 8,
      },
      {
        id: 74,
        name: "lamp 1",
        imageUrl: "https://i.ibb.co/5W6HfLg/kisspng-table-electric.png",
        price: 150,
        size: "large",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "lamp-1",
        like: 50,
        discount: 10,
        Piece: 8,
      },
      {
        id: 75,
        name: "lamp 2",
        imageUrl: "https://i.ibb.co/5rqfpdk/pngwing-com-9.png",
        price: 200,
        size: "medium",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "lamp-2",
        like: 60,
        discount: 10,
        Piece: 8,
      },
      {
        id: 76,
        name: "stairs bed",
        imageUrl: "https://i.ibb.co/18L6rJt/two-bed.png",
        price: 220,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "stairs-bed",
        like: 60,
        discount: 10,
        Piece: 8,
      },
      {
        id: 77,
        name: "Towel closet",
        imageUrl: "https://i.ibb.co/Pm4S3rq/towel-cabinet.png",
        price: 300,
        size: "medium",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen cupbord",
        link: "Towel-closet",
        like: 60,
        discount: 10,
        Piece: 8,
      },
      {
        id: 78,
        name: "double couch",
        imageUrl: "https://i.ibb.co/Tvct2yC/modern-couch.png",
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "double-couch",
        like: 60,
        discount: 10,
        Piece: 8,
      },
      {
        id: 79,
        name: "rose couch",
        imageUrl: "https://i.ibb.co/MCBLv9J/rose-couch.png",
        price: 50,
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "rose-couch",
        like: 60,
        discount: 10,
        Piece: 8,
      },
      {
        id: 80,
        name: "meeting desk",
        imageUrl: "https://i.ibb.co/QX9xRt7/metal-desk.png",
        price: 350,
        size: "medium",
        type: "office",
        url: "office",
        recomended: "meeting table",
        link: "meeting-desk",
        like: 60,
        discount: 10,
        Piece: 8,
      },
      {
        id: 81,
        name: "dark desk ",
        imageUrl: "https://i.ibb.co/HXhSV7V/black-desk.png",
        price: 150,
        size: "medium",
        type: "office",
        url: "office",
        recomended: "desk",
        link: "dark-des",
        like: 60,
        discount: 10,
        Piece: 9,
      },
      {
        id: 82,
        name: "Knife holder",
        imageUrl: "https://i.ibb.co/6JGTjqN/wodden-stand.png",
        price: 40,
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen tools",
        link: "Knife-holder",
        like: 60,
        discount: 10,
        Piece: 9,
      },
      {
        id: 83,
        name: "wooden spoons",
        imageUrl: "https://i.ibb.co/z76mLr5/spoon.png",
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen tools",
        link: "wooden-spoons",
        like: 60,
        discount: 10,
        Piece: 9,
      },
      {
        id: 84,
        name: "pyano",
        imageUrl: "https://i.ibb.co/pXpGFMZ/pyano.png",
        price: 25,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids toy",
        link: "pyano",
        like: 60,
        discount: 10,
        Piece: 9,
      },
      {
        id: 85,
        name: "glass lamp 1",
        imageUrl: "https://i.ibb.co/M51sZNJ/pngwing-com-3.png",
        price: 200,
        size: "large",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "glass-lamp-1",
        like: 60,
        discount: 10,
        Piece: 9,
      },
      {
        id: 86,
        name: "boys bed 2",
        imageUrl: "https://i.ibb.co/zJGWDrp/pngwing-com-6.png",
        price: 50,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "boys-bed-2",
        like: 60,
        discount: 10,
        Piece: 9,
      },
      {
        id: 87,
        name: "white cupbord",
        imageUrl: "https://i.ibb.co/Qm9GJYP/pngwing-com-3.png",
        price: 180,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "white-cupbord",
        like: 60,
        discount: 10,
        Piece: 9,
      },
      {
        id: 88,
        name: "brown cupbord",
        imageUrl: "https://i.ibb.co/qC8Kn4j/pngwing-com-12.png",
        price: 170,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "brown-cupbord",
        like: 60,
        discount: 10,
        Piece: 9,
      },
      {
        id: 89,
        name: "red couch",
        imageUrl: "https://i.ibb.co/LSsKqPY/red-couch.png",
        price: 50,
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "red-couch",
        like: 60,
        discount: 10,
        Piece: 9,
      },
      {
        id: 90,
        name: "dinner table",
        imageUrl: "https://i.ibb.co/zFPdSJz/date-table.png",
        price: 50,
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen tools",
        link: "dinner-table",
        like: 60,
        discount: 50,
        Piece: 9,
      },
      {
        id: 91,
        name: "modern couch",
        imageUrl: "https://i.ibb.co/Y0BMQmK/modern-s-couch.png",
        price: 30,
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "modern-couch",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 92,
        name: "floor cabinet",
        imageUrl: "https://i.ibb.co/RC0JF57/wooden-cabinet.png",
        price: 15,
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen tools",
        link: "floor cabinet",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 93,
        name: "brown bed",
        imageUrl: "https://i.ibb.co/PGTs8R0/pngwing-com-24.png",
        price: 800,
        size: "large",
        type: "bed room",
        url: "bed-room",
        recomended: "bed",
        link: "brown-bed",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 94,
        name: "b modern cupbord",
        imageUrl: "https://i.ibb.co/q5TThY1/pngwing-com-4.png",
        price: 1500,
        size: "large",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "b-modern-cupbord",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 95,
        name: "wall watch",
        imageUrl: "https://i.ibb.co/qxRX9zv/pngflow-com-1.png",
        price: 200,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "wall-watch",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 96,
        name: "golden lamb",
        imageUrl: "https://i.ibb.co/8cpmm7z/pngwing-com-11.png",
        price: 350,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "golden-lamb",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 97,
        name: "wooden bed",
        imageUrl: "https://i.ibb.co/PCGSC21/pngwing-com-8.png",
        price: 900,
        size: "large",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "wooden-bedk",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 98,
        name: "ship bed",
        imageUrl: "https://i.ibb.co/1QPcDLB/ship-bed.png",
        price: 1150,
        size: "large",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "ship-bed",
        like: 60,
        discount: 50,
        Piece: 6,
      },
      {
        id: 99,
        name: "wooden cupbord",
        imageUrl: "https://i.ibb.co/88d8Xr8/pngwing-com-2.png",
        price: 15,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "wooden-cupbord",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 100,
        name: "simple cupbord",
        imageUrl: "https://i.ibb.co/CPZzZkb/pngwing-com-1.png",
        price: 25,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "simple-cupbord",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 101,
        name: "modern gray couch",
        imageUrl: "https://i.ibb.co/9H1qNxk/modern-gray-couch.png",
        price: 30,
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "modern-gray-couch",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 102,
        name: "white desk",
        imageUrl: "https://i.ibb.co/B3ydN16/image-0000s-0000-white-table.jpg",
        price: 550,
        size: "medium",
        type: "office",
        url: "office",
        recomended: "desk",
        link: "white-0desk",
        like: 60,
        discount: 10,
        Piece: 6,
      },
      {
        id: 103,
        name: "small cupbord",
        imageUrl: "https://i.ibb.co/J5KJgYH/pngwing-com-8.png",
        price: 50,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "small-cupbord",
        like: 60,
        discount: 10,
        Piece: 8,
      },
      {
        id: 104,
        name: "dark couch",
        imageUrl: "https://i.ibb.co/hWSgj3S/dark-couch.png",
        price: 35,
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "dark-couch",
        like: 60,
        discount: 10,
        Piece: 8,
      },
      {
        id: 105,
        name: "white bed",
        imageUrl: "https://i.ibb.co/MVyjm0W/pngwing-com-3.png",
        price: 180,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "white-bed",
        like: 60,
        discount: 10,
        Piece: 8,
      },
      {
        id: 106,
        name: "l girls bed",
        imageUrl: "https://i.ibb.co/Hh0MqmM/pngwing-com-2.png",
        price: 120,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids bed",
        link: "l-girls-bed",
        like: 60,
        discount: 10,
        Piece: 8,
      },
      {
        id: 107,
        name: "roof lamp",
        imageUrl: "https://i.ibb.co/0KncN2H/pngwing-com-10.png",
        price: 600,
        size: "medium",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "roof lamp",
        like: 60,
        discount: 10,
        Piece: 8,
      },
      {
        id: 108,
        name: "dark cabinet",
        imageUrl: "https://i.ibb.co/b3FFxFN/wall-cabinet.png",
        price: 30,
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen tools",
        link: "dark-cabinet",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 109,
        name: "roof lamp 4",
        imageUrl: "https://i.ibb.co/VQdVkrs/pngwing-com-17.png",
        price: 170,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "lamb",
        link: "roof-lamp-4",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 110,
        name: "light gray couch",
        imageUrl: "https://i.ibb.co/2WsqCF4/light-gray-couch.png",
        price: 37,
        size: "small",
        type: "living room",
        url: "living-room",
        recomended: "small couch",
        link: "light-gray-couch",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 111,
        name: "spoons",
        imageUrl: "https://i.ibb.co/fpmnvgN/hiclipart-com-2.png",
        price: 30,
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen tools",
        link: "spoons",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 112,
        name: "big meeting table",
        imageUrl: "https://i.ibb.co/p2gBhK7/big-meeting-table.png",
        price: 950,
        size: "large",
        type: "office",
        url: "office",
        recomended: "meeting table",
        link: "big-meeting-table",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 113,
        name: "table",
        imageUrl: "https://i.ibb.co/7YsvvzP/table.png",
        price: 100,
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen table",
        link: "table",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 114,
        name: "white cupbord",
        imageUrl: "https://i.ibb.co/rZbYDTM/pngwing-com-10.png",
        price: 180,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "white-cupbord",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 115,
        name: "simple wooden cupbord",
        imageUrl: "https://i.ibb.co/0CmpgTF/pngwing-com-9.png",
        price: 220,
        size: "small",
        type: "bed room",
        url: "bed-room",
        recomended: "cupbord",
        link: "simple-wooden-cupbord",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 116,
        name: "horse",
        imageUrl: "https://i.ibb.co/pPvbVZy/horse.png",
        price: 150,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids toy",
        link: "horse",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 117,
        name: "kids car",
        imageUrl: "https://i.ibb.co/w4872Ns/babe-car.png",
        price: 150,
        size: "small",
        type: "for kids",
        url: "for-kids",
        recomended: "kids toy",
        link: "kids-car",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 118,
        name: "high wall cabinet",
        imageUrl: "https://i.ibb.co/jvj4nwt/wall-cabinet-2.png",
        price: 600,
        size: "medium",
        type: "kitchen",
        url: "kitchen",
        recomeded: "kitchen cupbord",
        link: "high-wall-cabinet",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 119,
        name: "Wooden spoons",
        imageUrl: "https://i.ibb.co/LRS5b3W/wood-spoon.png",
        price: 25,
        size: "small",
        type: "kitchen",
        url: "kitchen",
        recomended: "kitchen tools",
        link: "Wooden-spoons",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 120,
        name: "Chandeliers 3",
        imageUrl: "https://i.ibb.co/HFVCWTk/pngwing-com-12.png",
        price: 130,
        size: "small",
        type: "accessories",
        url: "accessories",
        recomended: "Chandeliers",
        link: "Chandeliers-3",
        like: 60,
        discount: 10,
        Piece: 4,
      },
      {
        id: 121,
        name: "modern desk",
        imageUrl: "https://i.ibb.co/TKCTvVB/wooden-desk.png",
        price: 500,
        size: "small",
        type: "office",
        url: "office",
        recomended: "desk",
        link: "modern-desk",
        like: 60,
        discount: 50,
        Piece: 4,
      },
      {
        id: 122,
        name: "basic desk",
        imageUrl: "https://i.ibb.co/zGXxq9c/basic-desk-2.png",
        price: 350,
        size: "small",
        type: "office",
        url: "office",
        recomended: "desk",
        link: "basic-desk",
        like: 250,
        discount: 10,
        Piece: 4,
      },
    ],
  },
};

export default SHOP_DATA;
