const SliderActionType = {
  FETCH_SLIDERS_START: " FETCH_SLIDERS_START",
  FETCH_SLIDERS_SSUCCESS: "FETCH_SLIDERS_SSUCCESS",
  FETCH_SLIDERS_FAILURE: "FETCH_SLIDERS_FAILURE",
};

export default SliderActionType;
